language: node_js
node_js:
- '5.1'
cache:
  directories:
  - node_modules
  - ".sass-cache"

env:
  global:
  - CREDENTIALS: "./.tedxftp"
  - FTP_DIR: "/web/"
  - GH_REPO_SLUG: itkpi/tedx
  - GH_REF: github.com/${GH_REPO_SLUG}.git
  - secure: aOkmFPtJsFLxOvzKFEyvh5PxNxZ/eU3MszSNX6XqNsKcoMCfA1ESMGe07pEpOp7xFkTLB+tG9ihGM+E24tv4yZuzZXc4+re7UC7S+2CuacKjJfvHUQPxpccDEEwes2njx3d1rYu58V3IyuBllsGnD9divPCZBxQMQ++WLk/RaPI=
  - secure: XMPFsq1xKadKyZMic4ATBGxbH65TswiKobCbWr/5CPErCiBNZSTsDz442v97334ALZGDuzgmRTLNerbeqhSRyiJjWF/YYZ7oAFbPZYAx0vtCnRpJXYI2QDia6NUEtjPCHFuxxnq8bceZ4ihPzHvw/Jgv3CbLr0uG9v8Cc8RblUc=
  - secure: deXaER9bsbpkPb/niIKraQcL3NP4OXVRNx33dDHWFHXHh7dQzc5c3EHaOQGk8PEVwmBJo+uQXOotTWfU5c8cu2Nr3WuQN0eyDwEtMguS3CXYuVPAlWZjocUdHFc625rcttdn8g3L3J1SuUeow3k0BD6aNJwaoRBZdo0Z3pG1Ae8=
  - secure: oipqUF6LdhkIoFi6s785EH8lq95ksWposlzazfS2RzFGbWbKhsa1B+mucwh8OU7BTX0CdZNKWdOei4wciz3A5Y7MtmWThgQ7oM72vTFQ9u/s3DmXSchyCgStzSgCsZf6Hg6PhHCl4c0hx54Fi+HybDVRZBLBwRw86cXxMz2o+FE=

addons:
  apt:
    packages:
    - pngquant
    - graphicsmagick-imagemagick-compat
    - ncftp
    - ruby
    - libnotify-bin
install:
- npm i -g gulp marked
- npm i --only=prod
- gem update --system
- gem install sass compass

script: make build

after_success: openssl aes-256-cbc -K $encrypted_5156c71c2a5e_key -iv $encrypted_5156c71c2a5e_iv -in .tedxftp.enc -out .tedxftp -d
deploy:
  - provider: script
    skip_cleanup: true
    on:
      repo: ${GH_REPO_SLUG}
      branch: master
      node_js: '5.1'
    script: make gh-deploy
  - provider: script
    skip_cleanup: true
    on:
      repo: ${GH_REPO_SLUG}
      branch: master
      node_js: '5.1'
    script: make ftp-deploy; rm -f $CREDENTIALS
