language: node_js
node_js:
- '5.1'
cache:
  directories:
  - node_modules
  - ".sass-cache"

env:
  global:
  - CREDENTIALS: "./.tedxftp"
  - FTP_DIR: "/web/"
  - GH_REPO_SLUG: itkpi/tedx
  - GH_REF: github.com/${TRAVIS_REPO_SLUG}.git
  - GH_REPO_URL: git://${TRAVIS_REPO_SLUG}
  - TEDX_V1_SHA: v1.2
  - secure: oipqUF6LdhkIoFi6s785EH8lq95ksWposlzazfS2RzFGbWbKhsa1B+mucwh8OU7BTX0CdZNKWdOei4wciz3A5Y7MtmWThgQ7oM72vTFQ9u/s3DmXSchyCgStzSgCsZf6Hg6PhHCl4c0hx54Fi+HybDVRZBLBwRw86cXxMz2o+FE=

addons:
  apt:
    packages:
    - pngquant
    - graphicsmagick-imagemagick-compat
    - ncftp
    - ruby
    - libnotify-bin
install:
- npm i -g gulp marked
- npm i --only=prod
- gem update --system
- gem install sass compass

script:
- make build
- git fetch --unshallow
- git fetch --tags
- git clone --branch ${TEDX_V1_SHA} .git build/old-website
#- git clone ${GH_REPO_URL} build/old-website
- cd build/old-website
- rm -rf .git
- cp -v ../../Makefile .
- make build
- cd ../..

after_success: openssl aes-256-cbc -K $encrypted_5156c71c2a5e_key -iv $encrypted_5156c71c2a5e_iv -in .tedxftp.enc -out .tedxftp -d
deploy:
  - provider: script
    skip_cleanup: true
    on:
      repo: ${GH_REPO_SLUG}
      branch: master
      node_js: '5.1'
    script: make gh-deploy
  - provider: script
    skip_cleanup: true
    on:
      repo: ${GH_REPO_SLUG}
      branch: master
      node_js: '5.1'
    script: make ftp-deploy; rm -f $CREDENTIALS
